Sisyphus/Models/Operation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sisyphus.Data;
using Sisyphus.TaskProviders;

namespace Sisyphus.Models
{
    public class Operation
    {
        [Key]
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }
        public Guid ProviderId { get; set; }
        public virtual Provider Provider { get; set; }
        public string Settings { get; set; }

        private object settingsObject;

        [NotMapped]
        public object SettingsObject
        {
            get
            {
                if ( settingsObject == null )
                {
                    var taskProvider = GetTaskProvider();
                    if ( taskProvider == null )
                    {
                        return null;
                    }
                    settingsObject = taskProvider.Settings;
                }
                return settingsObject;
            }
        }
        public TaskProvider GetTaskProvider()
        {
            if ( Provider == null )
            {
                return null;
            }
            var type = Type.GetType( Provider.FullyQualifiedTypeName );
            var taskProvider = ( TaskProvider ) Activator.CreateInstance( type, this );
            return taskProvider;
        }
    }
}

Sisyphus/ViewModels/OperationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Sisyphus.TaskProviders;

namespace Sisyphus.ViewModels
{
    public class OperationViewModel
    {
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public Guid ProviderId { get; set; }

        public object SettingsObject { get; set; }

        public IFormCollection FormCollection { get; set; }
    }
}

Sisyphus/Controllers/OperationsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Sisyphus.Data;
using Sisyphus.Models;
using Sisyphus.Services;
using Sisyphus.Utilities;
using Sisyphus.ViewModels;

namespace Sisyphus.Controllers
{
    public class OperationsController : Controller
    {
        private readonly DataContext dataContext;
        private readonly IOperationsService operationsService;
        public OperationsController( DataContext dc, IOperationsService opService )
        {
            dataContext = dc;
            operationsService = opService;
        }

        [Authorize( ClaimsPolicies.Administrator )]
        public IActionResult Index()
        {
            return View( dataContext.Operations.ToList() );
        }

        [Authorize( ClaimsPolicies.Administrator )]
        public IActionResult Edit( Guid id )
        {
            var operation = dataContext.Operations.Where( o => o.Id == id ).FirstOrDefault();

            var operationVM = new OperationViewModel();

            if ( operation != null )
            {
                operationVM.Id = operation.Id;
                operationVM.ProviderId = operation.ProviderId;
                operationVM.Name = operation.Name;
                operationVM.SettingsObject = operation.SettingsObject;
            }

            var providers = dataContext.Providers.ToList();
            if ( operation == null )
            {
                providers.Insert( 0, new Provider { Id = Guid.Empty, Name = "" } );
            }
            ViewBag.Providers = providers;

            return View( operationVM );
        }

        [Authorize( ClaimsPolicies.Administrator )]
        public IActionResult Export( Guid id )
        {
            var op = dataContext.Operations.Where( o => o.Id == id ).FirstOrDefault();
            var export = OperationExport.GetExport( op );
            var output = JsonConvert.SerializeObject( export );

            var stream = new MemoryStream();
            var writer = new StreamWriter( stream );
            writer.Write( output );
            writer.Flush();
            stream.Position = 0;
            return File( stream, "application/json", op.Name.Replace( " ", "_" ) + ".json" );
        }

        [Authorize( ClaimsPolicies.Administrator )]
        public IActionResult Settings( Guid id )
        {
            var provider = dataContext.Providers.Where( p => p.Id == id ).FirstOrDefault();
            var operation = new Operation
            {
                Provider = provider
            };

            return PartialView( "Settings", operation );
        }

        [HttpPost]
        [Authorize( ClaimsPolicies.Administrator )]
        public IActionResult Save( OperationViewModel operationViewModel )
        {
            operationsService.UpdateFromViewModel( operationViewModel );

            return Redirect( "/Operations" );
        }

        [Authorize( ClaimsPolicies.Administrator )]
        public async Task<IActionResult> Delete( Guid? id )
        {
            if ( id == null )
            {
                return NotFound();
            }

            var operation = await dataContext.Operations
                .FirstOrDefaultAsync( m => m.Id == id );
            if ( operation == null )
            {
                return NotFound();
            }

            ViewBag.Bundles = dataContext.BundleOpperations
                .Where( bo => bo.OperationId == id )
                .Select( bo => bo.Bundle )
                .ToList();

            return View( operation );
        }

        [HttpPost, ActionName( "Delete" )]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed( Guid id )
        {
            var bundle = await dataContext.Operations.FindAsync( id );
            dataContext.Operations.Remove( bundle );
            await dataContext.SaveChangesAsync();
            return RedirectToAction( nameof( Index ) );
        }

        [Authorize( ClaimsPolicies.Administrator )]
        public IActionResult Import()
        {
            return View();
        }

        [Authorize( ClaimsPolicies.Administrator )]
        [HttpPost]
        public IActionResult Import( FileUpload fileUpload )
        {
            var file = fileUpload.FormFile;
            using ( var stream = file.OpenReadStream() )
            {
                StreamReader reader = new StreamReader( stream );
                string export = reader.ReadToEnd();
                var operation = OperationExport.Import( export );
                return RedirectToAction( "Edit", new { id = operation.Id } );
            }
        }


        [Authorize( ClaimsPolicies.Administrator )]
        public IActionResult ExportAll()
        {
            var operations = dataContext.Operations.ToList();

            System.IO.File.Delete( "export.zip" );

            var zip = ZipFile.Open( "export.zip", ZipArchiveMode.Create );

            foreach ( var op in operations )
            {
                var export = OperationExport.GetExport( op );
                var output = JsonConvert.SerializeObject( export );

                var fileName = op.Name.Replace( " ", "_" ) + ".json";
                System.IO.File.WriteAllText( fileName, output );
                zip.CreateEntryFromFile( fileName, fileName );
                System.IO.File.Delete( fileName );
            }

            zip.Dispose();
            var stream = System.IO.File.Open( "export.zip", FileMode.Open );

            return File( stream, "application/zip", "export.zip" );
        }
    }
}

Sisyphus/Views/Operations/Delete.cshtml
@model Sisyphus.Models.Operation

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Operation</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor( model => model.Name )
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor( model => model.Name )
        </dd>
        <dt class="col-sm-2">
            Bundles:
        </dt>
        <dd class="col-sm-10">
            <ul>
                @foreach ( Bundle bundle in ViewBag.Bundles )
                {
                    <li>@bundle.Name</li>
                }
            </ul>
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Sisyphus/Views/Operations/Edit.cshtml
@model Sisyphus.ViewModels.OperationViewModel

@{
    ViewData["Title"] = "Edit";
}

<style>
    textarea {
        width:100%;
        height:100px;
    }
</style>

<h1>Operation @Model.Name</h1>
<hr />

<form asp-action="Save">
    @Html.HiddenFor( o => o.Id )
    <div class="form-group">
        @Html.LabelFor( o => o.Name )
        @Html.EditorFor( o => o.Name )
    </div>
    <div class="form-group">
        @Html.LabelFor( o => o.ProviderId, "Provider" )
        @Html.DropDownListFor( o => o.ProviderId, new SelectList( ViewBag.Providers, "Id", "Name" ) )
    </div>
    <div id="ProviderSettings">
        @Html.EditorFor( o => o.SettingsObject )
    </div>
    <input type="submit" value="Save" class="btn btn-primary" />
    <a href="/Operations" class="btn btn-link">Cancel</a>
</form>

@section Scripts {
    <script>
        $("#ProviderId").change(function () {
            $.ajax({
                url: '/Operations/Settings/' + $("#ProviderId").val(),
                dataType: 'html',
                success: function (data) {
                    $('#ProviderSettings').html(data);
                }
            });
        });
    </script>

    @{await Html.RenderPartialAsync( "_ValidationScriptsPartial" );}
}

Sisyphus/Views/Operations/Import.cshtml
@model Sisyphus.ViewModels.FileUpload
@{
    ViewData["Title"] = "Import";
}

<h1>Import Operation</h1>

<form asp-action="Import" enctype="multipart/form-data" method="post">
    <div class="form-group">
        <input asp-for="FormFile" type="file">
    </div>
    <div class="form-group">
        <input type="submit" value="Import" class="btn btn-primary" />
    </div>

</form>
<div>
    <a asp-action="Index">Back to List</a>

</div>

Sisyphus/Views/Operations/Index.cshtml
@model List<Operation>

@{
    ViewData["Title"] = "Index";
}

<h1>Operations</h1>

<hr />
<table class="table">
    <tr>
        <th>Name</th>
        <th>Actions</th>
    </tr>
    @foreach ( var op in Model )
    {
<tr>
    <td>@op.Name</td>
    <td>@Html.ActionLink( "Edit", "Edit", "Operations", new { id = op.Id }, new { @class = "btn btn-default" } ) </td>
    <td>@Html.ActionLink( "Export", "Export", "Operations", new { id = op.Id }, new { @class = "btn btn-default" } ) </td>
    <td>@Html.ActionLink( "x", "Delete", "Operations", new { id = op.Id }, new { @class = "btn btn-danger btn-sm" } ) </td>
</tr>
    }
</table>
<a asp-action="Edit" class="btn btn-outline-primary">New</a>
<a asp-action="Import" class="btn btn-outline-primary">Import</a>
<a asp-action="ExportAll" class="btn btn-outline-primary">Export All</a>


@section Scripts {
    @{await Html.RenderPartialAsync( "_ValidationScriptsPartial" );}
}

Sisyphus/Views/Operations/Settings.cshtml
@model Operation
    @Html.EditorFor( o => o.SettingsObject )